modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="true_end"
version="1.4"
displayName="True End"
displayURL="https://modrinth.com/mod/true_end"
logoFile="icon.png"
authors="Mystic Creations Team"
description="Defeated the dragon, but woke up in a familiar yet unknown place, shortly you realize it was all just a dream."

[[mixin]]
mixinClasses = ["net.justmili.trueend.mixin.Mixins"]

[[dependencies.true_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.true_end]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.true_end]]
    modId="curios"
    mandatory=false
    versionRange="[5.4.3,)"
    ordering="NONE"
    side="BOTH"

